#This is a Makefile
add:
	gcc hello.c prject_main.c -o a
LMS.o: LMS.c 
	gcc LMS.c 
project_main.o: project_main.c 
	gcc project_main.c
exec:
	./a
clean:
	rm -rf a
	rm -rf *.exe
	rm -rf *.o
